### PR TITLE
trillian: switch to chainguard/netcat

### PR DESCRIPTION
**Pull request by tuananh**
## Description of the change

Switch to chainguard/netcat image for multiarch support (amd64 and arm64)

Fixes: #500 

## Existing or Associated Issue(s)

#500 

## Checklist

- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). Where applicable, update and bump the versions in any associated umbrella chart
- [ ] Variables are documented in the `values.yaml` and added to the README.md. The [helm-docs](https://github.com/norwoodj/helm-docs) utility can be used to generate the necessary content. Use `helm-docs --dry-run` to preview the content.
- [ ] JSON Schema generated.
- [ ] List tests pass for Chart using the [Chart Testing](https://github.com/helm/chart-testing) tool and the `ct lint` command.

### CODE REVIEW

**Review by hectorj2f — APPROVED** [review]
lgtm

**Comment by sabre1041** [comment]
@tuananh would you be able to resolve the conflict?

**Comment by tuananh** [comment]
> @tuananh would you be able to resolve the conflict?

just rebase with main & resolve conflict

**Comment by sabre1041** [comment]
@tuananh everything looks good. Just need a bump on the chart version and we can merge

**Review by sabre1041 — APPROVED** [review]
LGTM

**Pull request merged**
