### PR TITLE
update fulcio image to use release v1.3.0

### PR DESCRIPTION
**Pull request by cpanato**
## Description of the change

- update fulcio image to use release v1.3.0

## Checklist

- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). Where applicable, update and bump the versions in any associated umbrella chart
- [x] Variables are documented in the `values.yaml` and added to the README.md. The [helm-docs](https://github.com/norwoodj/helm-docs) utility can be used to generate the necessary content. Use `helm-docs --dry-run` to preview the content.
- [ ] JSON Schema generated.
- [ ] List tests pass for Chart using the [Chart Testing](https://github.com/helm/chart-testing) tool and the `ct lint` command.

### CODE REVIEW

**Comment by haydentherapper** [comment]
@cpanato, can we hold off until tomorrow? Wanted to run through this process for the game day

**Comment by cpanato** [comment]
@haydentherapper sure, approve when you are ready :) no rush

**Review by hectorj2f — APPROVED** [review]
lgtm

**Review by priyawadhwa — APPROVED** [review]

**Comment by cpanato** [comment]
closing this already done in https://github.com/sigstore/helm-charts/pull/518

**Pull request closed without merging**
