### PR TITLE
Bump cosigned version

### PR DESCRIPTION
**Pull request by nsmith5**
#### Summary

Updates cosigned version to 1.7.1

#### Ticket Link

Related to #110 

#### Release Note

```release-note
* Updated cosigned version to 1.7.1
```

### CODE REVIEW

**Review by sabre1041 — APPROVED** [review]
LGTM

**Comment by cpanato** [comment]
I think we need to add the https://github.com/sigstore/cosign/blob/main/config/policy-webhook.yaml in the cosigned chart as well

**Comment by hectorj2f** [comment]
Yes, @cpanato is correct. We need to add the policy webhook.
@nsmith5  I am already working on a PR that adds it, as i mentioned here https://github.com/sigstore/helm-charts/issues/114.

**Comment by nsmith5** [comment]
Closing in favour of #116

**Pull request closed without merging**
