### PR TITLE
fix(chart): dedup imagePullSecrets in trillian and rekor

### LINKED ISSUE #738: imagePullSecrets defined twice in Trillian chart
**Description**

Setting imagePullSecrets in a Trillian values file fails the chart rendering.

```
➜ helm template trillian sigstore/trillian --set 'imagePullSecrets[0].name=regsecret' | polaris audit --audit-path - --only-show-failed-tests
ERRO[0000] Error parsing YAML: (yaml: unmarshal errors:
  line 85: mapping key "imagePullSecrets" already defined at line 33)
ERRO[0000] Error fetching Kubernetes resources yaml: unmarshal errors:
  line 85: mapping key "imagePullSecrets" already defined at line 33
```

This also impact the Rekor chart because of the dependency.

**Version**

```
NAME                    CHART VERSION   APP VERSION     DESCRIPTION
sigstore/trillian       0.2.22          1.6.0           Trillian is a log that stores an accurate, immu...
```

### PR DESCRIPTION
**Pull request by ndegory**
## Description of the change

imagePullSecrets is duplicated in the Trillian chart, which fails the rendering when trying to set an image pull secret.

## Existing or Associated Issue(s)

Closes #738

## Additional Information

 

```
➜ ct lint --lint-conf ./ct.yaml
Linting charts...
------------------------------------------------------------------------------------------------------------------------
 Charts to be processed:
------------------------------------------------------------------------------------------------------------------------
 rekor => (version: "1.4.1", path: "charts/rekor")
 trillian => (version: "0.2.23", path: "charts/trillian")
------------------------------------------------------------------------------------------------------------------------
"sigstore" already exists with the same configuration, skipping                                                                                                                                                                       
Linting chart "rekor => (version: \"1.4.1\", path: \"charts/rekor\")"
Checking chart "rekor => (version: \"1.4.1\", path: \"charts/rekor\")" for a version bump...
Old chart version: 1.4.0
New chart version: 1.4.1
Chart version ok.
Validating /Users/nicolas.degory/Code/src/github.com/sigstore/helm-charts/charts/rekor/Chart.yaml...
Validation success! 👍

Linting chart with values file "charts/rekor/ci/ci-values.yaml"...

==> Linting charts/rekor
[INFO] Chart.yaml: icon is recommended

1 chart(s) linted, 0 chart(s) failed
Linting chart "trillian => (version: \"0.2.23\", path: \"charts/trillian\")"
Checking chart "trillian => (version: \"0.2.23\", path: \"charts/trillian\")" for a version bump...
Old chart version: 0.2.22
New chart version: 0.2.23
Chart version ok.
Validating /Users/nicolas.degory/Code/src/github.com/sigstore/helm-charts/charts/trillian/Chart.yaml...
Validation success! 👍
==> Linting charts/trillian
[INFO] Chart.yaml: icon is recommended

1 chart(s) linted, 0 chart(s) failed

------------------------------------------------------------------------------------------------------------------------
 ✔︎ rekor => (version: "1.4.1", path: "charts/rekor")
 ✔︎ trillian => (version: "0.2.23", path: "charts/trillian")
------------------------------------------------------------------------------------------------------------------------
All charts linted successfully
```

I haven't updated the dependencies in scaffold and rekor, I suppose this PR has to be merged first and the trillian chart published to be able to update the Chart.lock.

## Checklist

- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). Where applicable, update and bump the versions in any associated umbrella chart
- [ ] Variables are documented in the `values.yaml` and added to the README.md. The [helm-docs](https://github.com/norwoodj/helm-docs) utility can be used to generate the necessary content. Use `helm-docs --dry-run` to preview the content.
- [ ] JSON Schema generated.
- [x] List tests pass for Chart using the [Chart Testing](https://github.com/helm/chart-testing) tool and the `ct lint` command.

### CODE REVIEW

**Comment by hectorj2f** [comment]
@ndegory Where do you see it duplicated in https://github.com/sigstore/helm-charts/blob/f02b411e081467206d680e601779f1c0c15ff024/charts/trillian/templates/mysql/deployment.yaml ? With your change, we are removing it from the deployment.

**Comment by ndegory** [comment]
@hectorj2f this file is after I removed one of the two imagePullSecrets from the template, and you can see one is left on line 46

**Comment by ndegory** [comment]
@hectorj2f , do we agree there's a duplication in current version of the trillian chart?

**Comment by ndegory** [comment]
@hectorj2f , this issue is now also in the latest rekor chart, you can see the double definition at these two lines:
https://github.com/sigstore/helm-charts/blob/rekor-1.4.0/charts/rekor/templates/mysql/deployment.yaml#L46
https://github.com/sigstore/helm-charts/blob/rekor-1.4.0/charts/rekor/templates/mysql/deployment.yaml#L99

**Comment by cpanato** [comment]
@ndegory please sign the DCO and split the changes in two PRs as they are for two different charts, thanks for the contribution!

**Comment by ndegory** [comment]
looks like @cmurphy applied the same fix in  #752 and got approved, so I'll close this one.

**Comment by cmurphy** [comment]
@ndegory sorry about that! Should have checked first.

**Comment by haydentherapper** [comment]
Thank you @ndegory for raising this!

**Pull request closed without merging**
