### PR TITLE
Add contributing.md with some guidelines

### LINKED ISSUE #298: Shouldn't the Chart.lock files be committed to pin the dependencies?
**Question**

Usually it is a good practice to commit lock files to ensure we pin to exactly the same version of a release. E.g. a tag could be replaced and therefore silently install another dependency.

I would propose to remove the exclusion from the Chart.lock from the .gitignore and pin all charts with dependencies by running.

```shell
helm dependency build
```

This will download a tgz, which we should add to the .gitignore.

Happy to provide a PR if you agree.

### PR DESCRIPTION
**Pull request by marcofranssen**
**Description of the change**

Add [CONTRIBUTING.md](https://github.com/marcofranssen/sigstore-helm-charts/blob/simplify-contributing/CONTRIBUTING.md) to ease contributions by community and having docs to point to when a PR does not comply with these guidelines.
Will also add the README.md.gotmpl templates for other charts once #297 and #299 are merged in this PR. Secondly I will ensure all charts have a lock file in place and committed.

 **Existing or Associated Issue(s)**

Resolves #298 

 **Additional Information**

 

**Checklist**

- [ ] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). Where applicable, update and bump the versions in any associated umbrella chart
- [ ] Variables are documented in the `values.yaml` and added to the README.md. THe [helm-docs](https://github.com/norwoodj/helm-docs) utility can be used to generate the necessary content. Use `helm-docs --dry-run` to preview the content
- [ ] JSON Schema generated
- [ ] List tests pass for Chart using the [Chart Testing](https://github.com/helm/chart-testing) tool and the `ct lint` command

### CODE REVIEW

**Review by cpanato — CHANGES_REQUESTED** [review]
any changes in the charts needs to be in separated PRs with a version bump as well


thanks for working on this

**Comment by marcofranssen** [comment]
> any changes in the charts needs to be in separated PRs with a version bump as well
> 
> thanks for working on this

Will move that to separate branches. Already considered that by isolating that in commits.

**Comment by marcofranssen** [comment]
See #301 for the docs and dependency lock.

**Comment by marcofranssen** [comment]
#299 is rebased on top of main and now also works.

**Review by cpanato — APPROVED** [review]
lgtm

**Review by hectorj2f — DISMISSED** [review]

**Comment by marcofranssen** [comment]
Made amistake earlier with rebasing the changes on a more recent main branch. Therefore also the #299 PR changes where included here. Now removed those commits from this PR again.

**Review by cpanato — APPROVED** [review]
thank you
if need any changes we can do in a follow up

**Pull request merged**
