### PR TITLE
[cosigned] Regenerate values schema

### PR DESCRIPTION
**Pull request by vpnachev**
#### Summary
Regenerate values schema for cosigned chart following the steps described in https://www.arthurkoziel.com/validate-helm-chart-values-with-json-schemas/. 

#### Ticket Link

Fixes

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Comment by hectorj2f** [comment]
You need to bump the Chart version here.

**Comment by vpnachev** [comment]
Done.
Sorry for the inconvenience, I was wondering should I do it or not when only the values schema file is changed.

**Comment by sabre1041** [comment]
@vpnachev since the schema is key metadata for a chart, we would want to bump the version whenever a change is made. 

Thanks for taking care of it!

**Review by cpanato — APPROVED** [review]

**Review by hectorj2f — APPROVED** [review]
lgtm, thanks :)

**Pull request merged**
