### PR TITLE
Enable custom annotations in Policy Controller pods

### LINKED ISSUE #766: Support custom annotations on Policy Controller pods
**Description**

Update the Policy Controller Helm chart to add support for custom annotations on controller pods.

Annotations are used widely used in Kubernetes to control behaviors such as metrics and log collection.

### PR DESCRIPTION
**Pull request by gsantos-hc**
## Description of the change

Add the ability to customize annotations on Policy Controller pods.

## Existing or Associated Issue(s)

Fixes #766 

## Checklist

- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). Where applicable, update and bump the versions in any associated umbrella chart
- [X] Variables are documented in the `values.yaml` and added to the README.md. The [helm-docs](https://github.com/norwoodj/helm-docs) utility can be used to generate the necessary content. Use `helm-docs --dry-run` to preview the content.
- [x] JSON Schema generated.
- [ ] List tests pass for Chart using the [Chart Testing](https://github.com/helm/chart-testing) tool and the `ct lint` command.

### CODE REVIEW

**Comment by cpanato** [comment]
please sign the DCO

**Comment by gsantos-hc** [comment]
Force-pushed to rebase from the latest `main` and update the chart version.

**Comment by vipulagarwal** [comment]
@gsantos-hc can you also update the [JSON schema](https://github.com/sigstore/helm-charts/blob/main/charts/policy-controller/values.schema.json) as well please?

**Comment by vipulagarwal** [comment]
LGTM

**Comment by gsantos-hc** [comment]
Force-pushed to rebase against latest `main`. Would it be possible to have this merged?

**Review by bobcallaway — APPROVED** [review]

**Pull request merged**
