### PR TITLE
Update rekor chart readme to match expected storageclass values

### PR DESCRIPTION
**Pull request by jeefy**
#### Summary
The current docs for the rekor helm chart don't reflect the actual storageClass values. This is a quick fix to realign the two. :) 

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Comment by cpanato** [comment]
need to bump the chart version @jeefy :)

thanks for fixing this

**Review by cpanato — CHANGES_REQUESTED** [review]
please bump the chart version

**Comment by jeefy** [comment]
Oh duh lol thanks

**Review by cpanato — APPROVED** [review]
thanks jeffy!

**Pull request merged**
