### PR TITLE
Fix cosigned chart documentation w.r.t. namespace selection and update to v1.5.2

### LINKED ISSUE #53: Cosigned Helm Chart Docs Improperly Use Label/Annotation Interchangeably
**Cosigned Helm Chart Docs Improperly Use Label/Annotation Interchangeably**

In [the docs](https://github.com/sigstore/helm-charts/tree/main/charts/cosigned#enabling-admission-control) the words "[annotation](https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/)" and "[label](https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/)" are used interchangeably, but are two different constructs in Kubernetes.

From testing, it appears as though to enable the cosigned admission webhook, you need to add `cosigned.sigstore.dev/include: "true"` as a label, not as an annotation.

### PR DESCRIPTION
**Pull request by vpnachev**
#### Summary
Fix cosigned chart documentation w.r.t. namespace selection and update to v1.5.2

#### Ticket Link

Fixes #53

#### Release Note

```release-note
The cosigned version have bee updated to v1.5.2.
```

### CODE REVIEW

**Review by cpanato — CHANGES_REQUESTED** [review]
thanks for the fix, can you please bump the chart version as well?

thanks again

**Comment by vpnachev** [comment]
I believe changing the chart versions deserves dedicated PR.
Could you point me to what needs to be changed where and I can open another PR?

**Comment by hectorj2f** [comment]
@vpnachev You could take as example this other PR https://github.com/sigstore/helm-charts/pull/47.

**Comment by vpnachev** [comment]
I have updated some versions based on the other similar changes, please take a look.

**Comment by vpnachev** [comment]
I just spotted that the chart is missing to configure the `metadata.namespace` for the role and rolebinding, therefore pushed [c76af63](https://github.com/sigstore/helm-charts/pull/61/commits/c76af63434c115b1dca3ffabfd0bfe1070417d5a) to this PR. If you think it is wrong, please let me know and I will drop it.

**Review by cpanato — APPROVED** [review]
thanks!

**Review by hectorj2f — APPROVED** [review]

**Pull request merged**
