### PR TITLE
Bump policy-controller version to v0.5.2

### PR DESCRIPTION
**Pull request by hectorj2f**
Signed-off-by: Hector Fernandez <hector@chainguard.dev>

## Description of the change
Bump policy-controller version to v0.5.2

## Checklist

- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). Where applicable, update and bump the versions in any associated umbrella chart
- [x] Variables are documented in the `values.yaml` and added to the README.md. The [helm-docs](https://github.com/norwoodj/helm-docs) utility can be used to generate the necessary content. Use `helm-docs --dry-run` to preview the content.
- [x] JSON Schema generated.
- [x] List tests pass for Chart using the [Chart Testing](https://github.com/helm/chart-testing) tool and the `ct lint` command.

### CODE REVIEW

**Review by cpanato — APPROVED** [review]
nice

**Comment by MageshSrinivasulu** [comment]
@hectorj2f I have one observation. Correct me if I am wrong

I have one last question. Based on the below image the policy will look for the secret named valid in the namespace where the pod is getting deployed right ?

image

But in the documentation, it says having that secret in the namespace where the policy controller deployed is sufficient. It seems both contradict.

image

Currently, it's expecting that valid secret to be present in all the namespaces where the image is getting deployed.

**Comment by hectorj2f** [comment]
@MageshSrinivasulu Correct! The secrets is linked to the namespace where the pod is been deployed. We can update the docs to reflect that 👍🏻. 

@MageshSrinivasulu could you create a PR in https://github.com/sigstore/docs/pull/40#pullrequestreview-1217639404 to make this change you suggested ?

**Comment by MageshSrinivasulu** [comment]
@hectorj2f Can you please approve this PR https://github.com/sigstore/docs/pull/44

**Pull request merged**
